### PR TITLE
pkg_add cookbook is now in Chef supermarket

### PR DESCRIPTION
**Pull request by vvanholl**

### CODE REVIEW

**Comment by mjbrender** [comment]
This is great @vvanholl! Did you run any tests to confirm it works? cc @basho-labs/chef-committers

**Comment by cheeseplus** [comment]
I am a little concerned with accepting this as it just appears that it was uploaded by a third party (@vvanholl) and not the actual maintainers of the cookbook itself. I would be more inclined to accept a PR or an issue that changes to the git HTTPS format instead of the `github:` shorthand as that will address issues from behind proxies. I'm happy to discuss this but generally speaking it's best that the maintainers of the cookbooks be the ones uploading to supermarket - there is no strict enforcement here but divorcing the supermarket artifact from the codebase can be very misleading/confusing for users.

**Comment by vvanholl** [comment]
mjbrender : tested with success.
cheeseplus : I have contacted the owners of the cookbook, waiting for response (hoping for it since last commit was 2 years ago).

The problem is actually, if you omit in your berkshelf file the line containing a reference to the cookbook github repository, you will have a very older version of riak cookbook.

Secondly, I can not really understand why in a cookbook hosted in supermarket, there are external references, for me that's not clean

**Comment by vvanholl** [comment]
Edit : the ownership of the cookbook on supermarket has just changed. Now the maintainers are owner of this cookbook.

**Comment by mjbrender** [comment]
Thanks for making that effort @vvanholl. Thoughts @basho-labs/chef-committers ?

**Comment by cheeseplus** [comment]
Thanks @vvanholl for doing this - I just want to set expectations correctly for new users but totally agree that this is the better way to do things.

**Pull request merged**
